baseURL: https://academic-folio.netlify.app
languageCode: en
title: Academic Folio
copyright: © Copyright 2023 The Academic Folio Contributors

enableRobotsTXT: true

module:
  imports:
  - path: github.com/rohandebsarkar/academic-folio/hugo-modules/svg-icons
  - path: github.com/rohandebsarkar/academic-folio/hugo-modules/responsive-images
