baseURL: https://academic-folio.netlify.app/
languageCode: en
title: Academic Folio
copyright: © Copyright 2023 The Academic Folio Contributors

module:
  imports:
  - path: github.com/adamaltmejd/hugo-icons
  - path: github.com/academic-folio/hugo-modules/responsive-images
