main:
  - identifier: home
    name: Home
    url: /
    weight: 10

  - identifier: blog
    name: Blog
    url: /blog/
    weight: 20

  - identifier: teaching
    name: Teaching
    url: /teaching/
    weight: 30
