main:
  - identifier: home
    name: Home
    url: /
    weight: 10

  - identifier: teaching
    name: Teaching
    url: /teaching/
    weight: 20

  - identifier: posts
    name: posts
    url: /posts/
    weight: 30
