[[main]]
  identifier= "Home"
  name= 'Home'
  url = '/'
  weight = 20

[[main]]
  identifier= "Teaching"
  name= 'Teaching'
  url = '/Teaching'
  weight= 25

#[[main]]
#  identifier = 'blog'
#  name = 'Blog'
#  title = 'blog section'
#  url = '/blog/'
#  weight = 30
