firstName: Albert
lastName: Einstein

email: einstein@example.org

description: Albert Einstein's personal website powered by the Academic Folio theme

# these tags would be added as keywords in metadata for website
tags:
- hugo
- hugo-theme
- academic-website
- al-folio

footerLastUpdated: true

recentPosts: 5 # number of recent posts to show in home page
showRecentPosts: true

recentNews: 5 # number of recent news to show in home page
showRecentNews: true

socialNavbar: true # show social icons on navbar
socialIndex: true # show social icons on index page

colorTheme: teal
