firstName: Albert
lastName: Einstein

email: einstein@example.org

description: Albert Einstein's personal website powered by the Academic Folio theme

footerLastUpdated: true

recentPosts: 5 # number of recent posts to show in home page
# set to 0 to disable
# I couldn't use this number in the template!
