baseURL = 'http://academic-folio.codeberg.page/'
languageCode = 'en'
title = 'Academic Folio'
copyright = '© Copyright 2023 The Academic Folio Authors'

[params]
firstName = 'You'
middleName = 'R.'
lastName = 'Name'
