baseURL = 'http://academic-folio.codeberg.page/'
languageCode = 'en'
title = 'Academic Folio'
copyright = '© Copyright 2023 The Academic Folio Authors'

[params]
  firstName = 'Albert'
  lastName = 'Einstein'

  email = 'einstein@example.org'

  description = "Albert Einstein's personal website powered by the Academic Folio theme"

  footerLastUpdated = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
