baseURL = 'https://rohandebsarkar.github.io/academic-folio/'
languageCode = 'en'
title = 'Academic Folio'
copyright = '© Copyright 2023 The Academic Folio Contributors'

[params]
  firstName = 'Albert'
  lastName = 'Einstein'

  email = 'einstein@example.org'

  description = "Albert Einstein's personal website powered by the Academic Folio theme"

  footerLastUpdated = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  identifier= "Home"
  name= 'Home'
  url = '/'
  weight = 20

[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = 'blog section'
  url = '/blog/'
  weight = 30

