baseURL = 'https://rohandebsarkar.github.io/academic-folio/'
languageCode = 'en'
title = 'Academic Folio'
copyright = '© Copyright 2023 The Academic Folio Contributors'

[params]
  firstName = 'Albert'
  lastName = 'Einstein'

  email = 'einstein@example.org'

  description = "Albert Einstein's personal website powered by the Academic Folio theme"

  footerLastUpdated = true
