main:
- name: Research
  url: /researches/
  weight: 1

- name: Teaching
  url: /teaching/
  weight: 2

- name: Scientific Events
  url: /events/
  weight: 3

- name: Curriculum Vitae
  url: /cv/
  weight: 4

social:
- name: email
  url: mailto:c.mettaversmessen@gmail.com
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://www.linkedin.com/username
  weight: 2
  params:
    icon: fab fa-linkedin

# - name: GitHub
#   url: https://github.com/username
#   weight: 3
#   params:
#     icon: fab fa-github

# - name: RSS Feed
#   url: /index.xml
#   weight: 4
#   params:
#     icon: fas fa-square-rss
